### ISSUE TITLE
Split up functions with behaviors dependent on the presence of keyword arguments for efficiency

### ISSUE THREAD

**Issue by sollyucko** [MSeifert04/iteration_utilities#222]
This would avoid unnecessary branching (checking for the presence of the argument) and allow for better optimization, especially if only positional arguments are allowed. Some examples are `consume` and `count_items`. I propose to split these into separate functions: `consume` to `advance` and `consume`, and `count_items` to `count_items`, `count_items` + `filter`, and `count_items` + `filter_eq`.

**Comment by MSeifert04** [comment]
The reason they are not split up was because I could simply re-use the same code and branch-prediction makes the branches much less costly. However I can see the point, especially because the splitted functions could have more descriptive names.

For the purpose of optimization, do you have any example(s) that you found were too slow or should be faster? It would make it easier to test/benchmark alternative approaches.

And thank you for raising the issue!

**Comment by sollyucko** [comment]
I haven't actually used this at all yet 😂. I just noticed this and was looking through the code a bit. I can work on a PR if you're interested when I get a chance. Also, shared portions can be moved to their  own functions. Keyword arguments should be allowed, even for single-argument functions, right?

**Comment by MSeifert04** [comment]
> I haven't actually used this at all yet 😂. I just noticed this and was looking through the code a bit

😄

---

I'm definitely interested in how these splitted-up functions would perform performance-wise. I'm not sure if it's worth the effort though. It's a bit of a trade-off between API surface and discoverability vs. performance vs. convenience vs. good names. But if it doesn't really improve the performance I don't know if it's worth changing the API and refactoring the internals. I'm not sure how many people use the library but making backwards-incompatible changes seems like an ideal way to annoy people using the library (if any). 😄

But if you like to make a PR or triage the performance of alternative approaches then I would be really interested!

**Comment by MSeifert04** [comment]
> Keyword arguments should be allowed, even for single-argument functions, right?

Ideally yes.

**Comment by sollyucko** [comment]
As for backwards compatibility, one option is to just come up with new names for the split-up versions. As for keyword arguments, AFAIK it's somewhat faster not to allow them, especially for single-argument functions, but it may or may not be worth the reduced usability. I'll just leave them as-is.

**Comment by sollyucko** [comment]
I'm trying to decide what I think of `all_monotone`. I dislike optional boolean parameters: If you want the default, should you state so explicitly? Not specify would lead to inconsistency between the default and its opposite. Specifying would lead to redundancy and would render the default pointless. It's too late to change now, though... In this case, to me, not specifying `decreasing` should mean that either is fine, not that it has to be `increasing`. I guess just leaving it is probably the best option at this point... Or perhaps a new function called `is_monotone` (which sounds slightly better to me) could be created, deprecating `all_monotone`, with `decreasing` defaulting to `None`, meaning that either direction is fine (and perhaps being changed to `increasing`, so that `1`/`True` signifies increase, and `0`/`False` signifies decrease), and `strict` either being required or staying as-is and defaulting to `False`?

**Comment by MSeifert04** [comment]
> As for backwards compatibility, one option is to just come up with new names for the split-up versions.

Yeah, that's probably the way to go.

> As for keyword arguments, AFAIK it's somewhat faster not to allow them, especially for single-argument functions

That's true, however it's almost always unnecessary optimization for functions processing iterables. It makes sense if the function is always `O(1)` because then constant factors matter more. However I don't have strong evidence to back this up - so I may be wrong!

> I dislike optional boolean parameters: If you want the default, should you state so explicitly?

I can see the point but this function was conceived as `is_sorted` equivalent (which explains the defaults) but with added options. I probably should've used `is_sorted` as name and made the keyword name `reversed`. 🤷‍♂️
That's actually my first own single-maintainer package and so it really doesn't surprises me that I made questionable API decisions. 😄

**Comment by sollyucko** [comment]
List of proposed changes:

- `all_monotone(iterable, decreasing=False, strict=False)` to `is_monotone(iterable, /, *, increasing=None, strict=False)`
- `chained(*funcs, /, reverse=False, all=False)` to:
  - `compose(*funcs, /, *, left_inner=False)` and/or `pipeline(*funcs, /, *, left_inner=True)`
  - `call_multiple(*funcs, /)`, which can either take 2 or more values as separate arguments, or take a single iterable, and returns a function that takes any number of positional and/or named arguments, and returns an iterable (to allow an infinite iterable of functions).
- `combinations_from_relations(dictionary, r)` to `combinations_from_relations(dictionary, r=None)`
- `consume(iterator, n)` to:
  - `consume_all(iterator)` or `advance_to_end(iterator)`
  - `advance(iterator, n)`

Also, some functions had incorrect argument specifications for optional arguments are different: `accumulate`, `argmax`, `argmin`, `combinations_from_relations`, `consume`, `groupedby`, `grouper`, `minmax`, `nth`.

There are also various functions that violate the SRP by adding keyword arguments to do additional things that could also be done with function composition, for possible, marginal speed and readability improvements ([Coconut](http://coconut-lang.org) would solve the readability problems): `argmax`, `argmin`, `argsorted`, `count_items`, `groupby`, `nth`, `sideeffects`.

Why is `nth` partially curried and why is it the only one? Why not just use `functools.partial`?

Why are `random_product` and `repeatfunc` documented as taking variable keyword arguments?

Isn't `return_identity` just `identity`?

Is there any pattern for when underscores are used in function names?

As for the questionable API decisions, if there are enough of them, you could consider making a fork of it with a related name. (`iteration_utilities_2`?)

**Comment by MSeifert04** [comment]
I'm sorry that I haven't answered until now. 

> Also, some functions had incorrect argument specifications for optional arguments are different:  [...]

I had a quick look and I'm not sure what you mean. Could you add at least one example where these are different so that I can fix it?

> There are also various functions that violate the SRP by adding keyword arguments to do additional things that could also be done with function composition

Yes, that's true. But I found that some compositions are tricky to get right or I had a use-case for this particular combination (and needed fast performance). I'm not particularly keen on changing these just for the sake of SRP.

> Why is nth partially curried and why is it the only one?

Because I had `first` and `last` before I added `nth`. By making it "curried" I could keep the API.

> Why are random_product and repeatfunc documented as taking variable keyword arguments?

What do you mean with variable keyword arguments?

> Isn't return_identity just identity?

Yep.

> Is there any pattern for when underscores are used in function names?

No, I haven't thought about this yet 😅 

> As for the questionable API decisions, if there are enough of them, you could consider making a fork of it with a related name. (iteration_utilities_2?)

Well, in theory this package is still alpha/beta because I never released a 1.x. However I wouldn't break API without a good reason - deprecation and renaming is easy enough to do without the need for breaking APIs or forking the library.

By the way: Thanks a lot for the assessment.

I would be especially interested in clarification on the documentation problems, if the docs are unclear or something is buggy that's something I want to fix fast. I do need some more time to think about ways to deal with the API changes. If you want to make one or multiple PRs (in case: keep them one issue for each PR) I'm very happy to review these, but don't feel pressured.

**Comment by sollyucko** [comment]
>> Also, some functions had incorrect argument specifications for optional arguments are different: [...]
> I had a quick look and I'm not sure what you mean. Could you add at least one example where these are different so that I can fix it?

I think that was typoed. What I meant is that either:

1. Specifying the default has a different behavior from omitting the argument. (E.g. `accumulate`'s `start` parameter.)
2. The argument is optional but not documented as such in the argspec. (E.g. `argmin`'s `key` and `default` parameters.)

Parameters for which specifying a particular value is equivalent to not specifying the argument at all should use <code>*name* = *default*</code>. Parameters for which there is no value that can be specified that would have identical behavior to not specifying any should use <code>[*name*]</code>.

>> Why are random_product and repeatfunc documented as taking variable keyword arguments?
> What do you mean with variable keyword arguments?

https://docs.python.org/3/library/inspect.html#inspect.CO_VARKEYWORDS

> ## <code>inspect.**CO_VARKEYWORDS**</code>
> The code object has a variable keyword parameter (`**kwargs`-like).

I was wondering why `repeatfunc`'s `times` and `random_product`'s `repeat` are documented as being `**kwargs`-like: `**times` and `**repeat`. Arguments after `*` or `*args` are keyword-only, which I guess is what you were trying to document.

> I would be especially interested in clarification on the documentation problems, if the docs are unclear or something is buggy that's something I want to fix fast. I do need some more time to think about ways to deal with the API changes. If you want to make one or multiple PRs (in case: keep them one issue for each PR) I'm very happy to review these, but don't feel pressured.

When I have a chance, I can submit PRs for some of these.

**Comment by MSeifert04** [comment]
> Parameters for which specifying a particular value is equivalent to not specifying the argument at all should use name = default. Parameters for which there is no value that can be specified that would have identical behavior to not specifying any should use [name]

Unfortunately `[name]` is not a valid Python signature. I already have the docstring-like signature so the C-functions are inspectable, I'm not sure if I want yet another place to put the signature.

> I was wondering why repeatfunc's times and random_product's repeat are documented as being **kwargs-like: **times and **repeat. Arguments after * or *args are keyword-only, which I guess is what you were trying to document.

Yeah, unfortunately Python 2.x does not support keyword-only arguments so this is not possible. Yes, it would be time to drop Python 2.x support but I simply haven't done that (yet).

> When I have a chance, I can submit PRs for some of these.

That would be great. But if you don't have the time that's also okay. I was simply curious.

**Comment by sollyucko** [comment]
> Unfortunately `[name]` is not a valid Python signature. I already have the docstring-like signature so the C-functions are inspectable, I'm not sure if I want yet another place to put the signature.

AFAIK, the convention is used throughout the standard library for C modules. It is also used by Argument Clinic: https://docs.python.org/3/howto/clinic.html#optional-groups

> To specify an optional group, add a `[` on a line by itself before the parameters you wish to group together, and a `]` on a line by itself after these parameters.

> Yeah, unfortunately Python 2.x does not support keyword-only arguments so this is not possible.

1. So are you unable to put non-`**kwargs` parameters after `*args`?
2. Shouldn't it still be documented normally?

**Comment by MSeifert04** [comment]
> AFAIK, the convention is used throughout the standard library for C modules. It is also used by Argument Clinic: https://docs.python.org/3/howto/clinic.html#optional-groups

That sounds interesting, but if I remember correctly then CPython documents the function signaturs in the documentation files, it doesn't use argument clinic to generate these. And that's what I want to avoid although it could be interesting in the cases where the documented signature isn't correct.

> 1. So are you unable to put non-**kwargs parameters after *args?

Yes, that's the limitation.

> 2. Shouldn't it still be documented normally?

What do you mean by "normally" here? Do you mean generating the documentation from the real function signature? If yes, then I tend to prefer this, because it's least effort to maintain and always "correct". But I haven't really investigated this fully, there may be something obvious I'm missing.

I like that the documented signature is identical to the signature one can get at runtime through `inspect`.

**Comment by sollyucko** [comment]
> Unfortunately `[name]` is not a valid Python signature. I already have the docstring-like signature so the C-functions are inspectable, I'm not sure if I want yet another place to put the signature.

> That sounds interesting, but if I remember correctly then CPython documents the function signaturs in the documentation files, it doesn't use argument clinic to generate these. And that's what I want to avoid although it could be interesting in the cases where the documented signature isn't correct.

> I like that the documented signature is identical to the signature one can get at runtime through `inspect`.

Yeah, apparently a lot of builtins aren't inspectable, even in Python 3. I do feel like it's better to have missing introspection than incorrect introspection, though.

> Yeah, unfortunately Python 2.x does not support keyword-only arguments so this is not possible. Yes, it would be time to drop Python 2.x support but I simply haven't done that (yet).

Many library authors have pledged to drop Python 2 support sometime before [2020-01-01](https://pythonclock.org/). https://python3statement.org/ I am basically ignoring Python 2 (and even older versions of Python 3) when I write my code. It's up to you to decide, though.

**Comment by MSeifert04** [comment]
Hey @sollyucko and sorry for the long delay. 

You made some very good points and made me aware of several of the problematic decisions I have made when I started the project. However I am currently more inclined to keep the library as it is and avoid deprecations or other version-related problems with users for now.

Thank you for bringing this up 👍
