### ISSUE TITLE
Python 3.11 or 3.10 support, and alternatives

### ISSUE THREAD

**Issue by blakeNaccarato** [MSeifert04/iteration_utilities#333]
### Edit

I modified this issue title to request support for Python 3.11 as well as (or instead of) 3.10. I also identify a workaround and an alternative package to `iteration_utilities` below.

I understand that life gets in the way and projects can easily get pushed to the back-burner and eventually off the stove and into unmaintained status 😅. In fact, your package still works fine as long as users have proper build tools installed. This is usually the case for users on Unix-like machines.

### Workaround for Windows users

This can be a tall order for Windows users, who don't have build tools out of the box and must install them. Install [Visual Build Tools 2022](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022) (tick the box for C++ build tools and perform the ~7GB install), reboot, and you will be able to successfully `pip install iteration-utilities`. This will also fix issues with packages which depend on `iteration_utilities`. 

### Alternatives

There are a few ways to replace your dependency on `iteration_utilities` if you wish to generalize your app to be easy to install for Windows and Unix-like users alike:

- Check out how the Copier project replaced (https://github.com/copier-org/copier/issues/889) their dependency on `iteration_utilities` with something called `funcy` ([PyPI](https://pypi.org/project/funcy/), [repo](https://github.com/Suor/funcy), [docs](https://funcy.readthedocs.io/en/stable/#)). They specifically needed deep flattening, which was a straight dependency swap. `funcy` may not be feature-equal with `iteration_utilities`, but it covers lots of the bases.
- Check out [the author of `iteration_utilities`'s recommendations](https://iteration-utilities.readthedocs.io/en/latest/#module-iteration_utilities) (see refs in the first paragraph) for possible substitutes to functions in `iteration-utilities`, which may be able to satisfy your dependency.
- Roll your own functions, as in this pure Python `deepflatten` implementation found in the Copier issue above. https://github.com/wilsonwaters/copier/blob/b72bc87e74542d931369c77f7e27681737812181/copier/tools.py#L154-L169.
- Consider compiling wheels for various architectures for `iteration_utilities` and contributing them back to this project by getting in contact with the owner.

### Original comment

Hello. Thank you for the latest bump to support Python 3.9. Are there plans to support Python 3.10 as well? At least one package (copier-org/copier) would benefit from this support.

**Comment by MSeifert04** [comment]
Hey @blakeNaccarato 

thank you for opening the issue. Unfortunately the github actions workflows are "a bit" oudated. I'll have a look at it in the next days.

Is the package actually not supporting Python 3.10 or are just the wheels missing?

**Comment by blakeNaccarato** [comment]
Yes it's just the wheels missing from PyPi for my particular arch, 64-bit Windows 10 on Python 3.10. In fact I can build it on a similar machine that I happen to have the build tools on.

I'm using the self-built package in service of `copier` and it seems to work fine, but `copier` only depends on `deepflatten`, so it's probably not the most robust test.

**Comment by blakeNaccarato** [comment]
Specifically the wheel that I can build for myself on my more developer-focused machines is `iteration_utilities-0.11.0-cp310-cp310-win_amd64.whl`.

I also checked out the repo at the 11.0.0 tag, as well as at HEAD, and ran your test suite. 1288/1288 tests passed on my machine. So that's a good sign!

**Comment by MSeifert04** [comment]
Thank you for checking the test suite. If it compiles and the tests work it's probably just updating the github actions so I can build the wheels for the different OSes. I think I can allocate some time in the next days (probably weekend) to do that.

**Comment by blakeNaccarato** [comment]
Thanks for looking into it. Also, please don't feel pressured to highly prioritize this, as I can still manage to build my own wheel for 0.11.0 in the meantime, and it's not a major blocking issue over at copier-org/copier in any case. It's just a nice-to-have for the future.

**Comment by MSeifert04** [comment]
Yeah, I think having Python 3.10 wheels might be really good - especially because most Windows users won't have a C compiler at hand. 
I also might some good progress today and I can confirm that Python 3.10 doesn't break anything. However it will take me a few more days to get this in a state where I can comfortably publish additional wheels on pypi. However if you need additional wheels the pipeline did create some wheels that passed the tests: https://github.com/MSeifert04/iteration_utilities/actions/runs/2008739611 (you may need to scroll down a bit)

**Comment by blakeNaccarato** [comment]
Hello again. Just checking in to see what is left to do regarding Python 3.10 support, and if there is any way I can help you?

Of course I understand that CICD and release workflows are just about the least user-friendly for a drive-by contributor, but I figured I'd offer to help nonetheless. 😅

**Comment by MSeifert04** [comment]
Sorry for dropping the ball on this, I'm currently pretty much swamped by work and private live. Just no energy and time to wrap up the commit.

**Comment by MSeifert04** [comment]
Thank you for offering help :)

But most of what needs to be done is stuff where I need to decide how I want to develop the package in the future (or not) and what I want to support (or not).

**Comment by blakeNaccarato** [comment]
No worries, I figured that the main blockers were big-picture things.

If you do end up deciding to put out a call for maintainers, I'm sure that asking around in a community like the [Python Discord](https://www.pythondiscord.com/) could help point you in the right direction.

**Comment by grbd** [comment]
Ran into this problem myself recently under windows, as a quick fix I just dropped down to python 3.9

**Comment by zlogz101** [comment]
@MSeifert04 Hi Michael, is there any plan to publish wheel for python 3.10? It's a block issue for us to upgrade to latest python now. Looking forward to seeing progress, and many thanks for your supporing in advance :)

**Comment by ningen1** [comment]
Hi any update for 3.10 ?

**Comment by swiedernix** [comment]
Any Update in 3.10 or 3.11?

**Comment by blakeNaccarato** [comment]
I've updated [my top-level comment](https://github.com/MSeifert04/iteration_utilities/issues/333#issue-1170178709) with some useful information, including a workaround for Windows users and some leads on replacing your dependency on `iteration_utilities`.

**Comment by MSeifert04** [comment]
Based on the great work of @fcollonval there is now a new release of `iteration_utilities` including wheels for Python 3.10, 3.11, and 3.12. 🎉 

But that's as far as the (purely) good news goes. I also want to include a word of caution and the future of the library at this point.

I cannot promise that such a situation might not happen again in the future. While this project is still very fascinating to me, I just haven't found the time to really dig into the new toolchains (and changes) surrounding Python with C extensions. I will attempt to find some more free time to keep up-to-date with the build-tools so that such a missing-wheels situation hopefully won't go unaddressed for that long.

I have also considered asking for an additional maintainer but I wouldn't accept someone that I don't know personally because the risk of a "random" person hijacking the package and including malware (or other nefarious things) is something I don't want to take. And unfortunately I've read about such incidents a few times...

In summary: I hope I can keep the package in working condition in the future. Probably not always instantaneous, but hopefully it will only be days/weeks instead of years. I'm also not planning to add new features at this point in time. I'm not saying it won't happen, but at the moment I'm not using Python much and thus don't need additional stuff.

---

Also I cannot recommend to add this (or any) library as a **dependency of libraries or production code** if you're only using **one** function from the package and you don't **really** need the better performance (some of the) functions here provide over alternatives. 
Additional dependencies carry risks, especially if it's a C extension based library like `iteration_utilities`. If there's a bug in the code it might have more serious consequences than just an unexpected result or exception.[1] And this library has only one maintainer (me).
Always make sure the utility/usability of the library outweighs the risks for you!

I don't want to discourage the use of this project for fun and personal projects. And if you're actually using `iteraton_utilities` in a library or production feel free to drop a issue in this repo. I would love to hear what you've been doing with the library 😍 

[1] I do have a lot of tests to minimize that risk and prevent regressions, but that's no guarantee there's no problem in the code. If you ever find a exploitable bug in the C code of a public function in my library I will do my best (and fast) to fix it or if that's not possible, remove the affected release from PyPI.
