### ISSUE TITLE
flatten drop empty lists instead of keeping them as null

### ISSUE THREAD

**Issue by ahmed-mahmood-hanafy** [MSeifert04/iteration_utilities#336]
Hi thanks for the library
I was counting on the index of the list so the code could behave correctly, lastly I used pandas but hope no one face the same bug again
the function drop empty lists instead of keeping them as null which change the index
![image](https://user-images.githubusercontent.com/48698528/192617834-40b91aae-f603-4b4c-b981-40f2a51e6862.png)

**Comment by MSeifert04** [comment]
Hello @ahmed-mahmood-hanafy and sorry for the very late reply. But thank you for making an issue

It's hard to reproduce the issues without having your dataframe or sheet. But given the description I think you have the equivalent of:

```
>>> from iteration_utilities import flatten
>>> list(flatten([[1], [], [2]]))
[1, 2]
```

And it's by design of `flatten` that it "drops" empty lists that are in there. Otherwise this would create ambiguity with `[[1], [None], [2]]` and `[[1], [], [2]]` inputs.

If I misunderstood your issue please reopen or open a new issue (I will do my best to respond more timely).

**Comment by ahmed-mahmood-hanafy** [comment]
Never mind Thanks for the replay and the library Yes it is as you explained sorry for the late reply
